// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Entities;

public partial class Question
{
    public int QuestionId { get; set; }

    public int Grade { get; set; }

    public int? TypeId { get; set; }

    public string QuestionHead { get; set; }

    public virtual ICollection<QuestChoice> QuestChoices { get; set; } = new List<QuestChoice>();

    public virtual ICollection<QuestModelanswer> QuestModelanswers { get; set; } = new List<QuestModelanswer>();

    public virtual ICollection<StdQuesExam> StdQuesExams { get; set; } = new List<StdQuesExam>();

    public virtual QuesType Type { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}