// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ExaminationSystem.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ExaminationSystem.Context
{
    public partial interface IExaminationContextProcedures
    {
        Task<int> SP_DeleteExamAsync(int? ExamID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_DeleteExam_QuesAsync(int? EID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_ExamAnswersAsync(int? ExamID, int? Std_ID, string Answers, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_ExamCorrectionResult>> SP_ExamCorrectionAsync(int? ExamID, int? Std_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_GenerateExamAsync(string courseName, int? NumberOfTrueOrFalse, int? NumberOfSingleChoice, int? Duration, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_UpdateInstructorAsync(int? InstructorID, string InstructorName, int? Salary, string Degree, int? Dept_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> SP_UpdateStudentAsync(int? SID, string FName, string LName, string address, string gender, DateOnly? Bdate, string Pnumber, int? deptID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
