// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Entities;

public partial class Instructor
{
    public int InsId { get; set; }

    public string InsName { get; set; }

    public int Salary { get; set; }

    public string Degree { get; set; }

    public int? DeptId { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual Department Dept { get; set; }

    public virtual ICollection<InstructorLogin> InstructorLogins { get; set; } = new List<InstructorLogin>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<Student> Stds { get; set; } = new List<Student>();
}