// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Entities;

public partial class StdCr
{
    public int StdId { get; set; }

    public int CourseId { get; set; }

    public double? StdGrade { get; set; }

    public virtual Course Course { get; set; }

    public virtual Student Std { get; set; }
}