// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Entities;

public partial class StudentLogin
{
    public string UserName { get; set; }

    public string Password { get; set; }

    public int? StdId { get; set; }

    public virtual Student Std { get; set; }
}