// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Entities;

public partial class Topic
{
    public int TopicId { get; set; }

    public int CourseId { get; set; }

    public string TopicName { get; set; }

    public virtual Course Course { get; set; }
}